package tis.com.test.common;

import org.springframework.test.context.ContextConfiguration;

@ContextConfiguration(locations = {
		"file:src/main/webapp/WEB-INF/config/egovframework/springmvc/egov-com-servlet.xml",
		"file:src/main/resources/egovframework/spring/com/context-aspect.xml",
		"file:src/main/resources/egovframework/spring/com/context-common.xml",
		"file:src/main/resources/egovframework/spring/com/context-datasource.xml",
		"file:src/main/resources/egovframework/spring/com/context-egovuserdetailshelper.xml",
		"file:src/main/resources/egovframework/spring/com/context-excel.xml",
		"file:src/main/resources/egovframework/spring/com/context-mail.xml",
		"file:src/main/resources/egovframework/spring/com/context-properties.xml",
		"file:src/main/resources/egovframework/spring/com/context-security.xml",
		"file:src/main/resources/egovframework/spring/com/context-sqlMap.xml",
		"file:src/main/resources/egovframework/spring/com/context-transaction.xml",
		"file:src/main/resources/egovframework/spring/com/context-validator.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Adbk.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-AdministCodeRecptn.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-AnswerNo.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-BatchOpert.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-BatchResult.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-bbs.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Cmt.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-CpyrhtPrtcPolicy.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-DeptJob.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-deptSchdulManage.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-diaryManage.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Epay.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-File.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Group.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-IndvdlPge.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-InfrmlSanctn.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-InsttCodeRecptn.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-LeaderSchdu.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-LoginLog.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-MailMsg.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-MemoReprt.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-MemoTodo.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Mgt.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Ncrd.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-RestDe.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Role.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Scrap.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-StplatManage.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-StsfdgNo.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-SysLog.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Tis.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-Tmplat.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-TrsmrcvLog.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-TrsmrcvMntrngLog.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-UsrCnfrm.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-WebLog.xml",
		"file:src/main/resources/egovframework/spring/com/idgn/context-idgn-WikMnthngReprt.xml",
		"file:src/main/resources/egovframework/spring/com/scheduling/context-scheduling-sym-bat.xml",
		"file:src/main/resources/egovframework/spring/com/scheduling/context-scheduling-sym-ccm-icr.xml"}
)

public class TisApplicationContextTestBase {
}
